feat: add fontawesome import rules
bothrs/eslint-config pull request #23
Opened 2022-10-04 14:37 UTC by TijsM

## What

- add fontawesome import rules

https://eslint.org/docs/latest/rules/no-restricted-imports

2022-10-04 14:40 UTC, JaccoGoris approved these changes

2022-10-10 08:31 UTC, FabianMeul requested changes

2022-10-10 08:31 UTC, FabianMeul commented on src/react-native.js
> +        paths: [
REQ:

Seems like you missed one;

```
paths: [
    '@fortawesome/free-solid-svg-icons',
    '@fortawesome/free-brands-svg-icons',
    '@fortawesome/free-regular-svg-icons',
    '@fortawesome/pro-solid-svg-icons',
    '@fortawesome/pro-regular-svg-icons',
    '@fortawesome/pro-light-svg-icons',
    '@fortawesome/pro-thin-svg-icons', // <-- Missing!
    '@fortawesome/pro-duotone-svg-icons',
    '@fortawesome/sharp-solid-svg-icons',
],
```

2022-10-10 08:36 UTC, FabianMeul approved these changes

2022-10-10 08:37 UTC, merged

2022-10-10 08:37 UTC, FabianMeul commented
:tada: This PR is included in version 1.8.0 :tada:

The release is available on:
- [GitHub release](https://github.com/bothrs/eslint-config/releases/tag/release/v1.8.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@bothrs/eslint-config/v/1.8.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: